import type { GitCommit, GitCommitFile, Project } from '@developer-memory/shared-types';
export declare const useGitStore: import("pinia").StoreDefinition<"git", Pick<{
    commits: import("vue").Ref<{
        id: string;
        hash: string;
        shortHash: string;
        authorName: string;
        authorEmail: string | null;
        authoredAt: string;
        committerName: string | null;
        committerEmail: string | null;
        committedAt: string;
        subject: string;
        body: string | null;
        parentHashes: string[];
        branchNames: string[];
        tagNames: string[];
        filesChanged: number;
        insertions: number;
        deletions: number;
    }[], GitCommit[] | {
        id: string;
        hash: string;
        shortHash: string;
        authorName: string;
        authorEmail: string | null;
        authoredAt: string;
        committerName: string | null;
        committerEmail: string | null;
        committedAt: string;
        subject: string;
        body: string | null;
        parentHashes: string[];
        branchNames: string[];
        tagNames: string[];
        filesChanged: number;
        insertions: number;
        deletions: number;
    }[]>;
    selected: import("vue").Ref<{
        id: string;
        hash: string;
        shortHash: string;
        authorName: string;
        authorEmail: string | null;
        authoredAt: string;
        committerName: string | null;
        committerEmail: string | null;
        committedAt: string;
        subject: string;
        body: string | null;
        parentHashes: string[];
        branchNames: string[];
        tagNames: string[];
        filesChanged: number;
        insertions: number;
        deletions: number;
    } | null, GitCommit | {
        id: string;
        hash: string;
        shortHash: string;
        authorName: string;
        authorEmail: string | null;
        authoredAt: string;
        committerName: string | null;
        committerEmail: string | null;
        committedAt: string;
        subject: string;
        body: string | null;
        parentHashes: string[];
        branchNames: string[];
        tagNames: string[];
        filesChanged: number;
        insertions: number;
        deletions: number;
    } | null>;
    files: import("vue").Ref<{
        id: string;
        relativePath: string;
        previousPath: string | null;
        changeType: string;
        insertions: number | null;
        deletions: number | null;
    }[], GitCommitFile[] | {
        id: string;
        relativePath: string;
        previousPath: string | null;
        changeType: string;
        insertions: number | null;
        deletions: number | null;
    }[]>;
    project: import("vue").Ref<{
        id: string;
        name: string;
        path: string;
        framework: string | null;
        language: string | null;
        hasGit: boolean;
        indexStatus: import("@developer-memory/shared-types").ProjectIndexStatus;
        lastIndexedAt: string | null;
        indexedFileCount: number;
        indexError: string | null;
        gitSyncStatus: "NOT_SYNCED" | "SYNCING" | "SYNCED" | "FAILED";
        lastGitSyncedAt: string | null;
        gitCommitCount: number;
        gitCurrentBranch: string | null;
        gitHeadHash: string | null;
        gitSyncError: string | null;
        createdAt: string;
        updatedAt: string;
    } | null, Project | {
        id: string;
        name: string;
        path: string;
        framework: string | null;
        language: string | null;
        hasGit: boolean;
        indexStatus: import("@developer-memory/shared-types").ProjectIndexStatus;
        lastIndexedAt: string | null;
        indexedFileCount: number;
        indexError: string | null;
        gitSyncStatus: "NOT_SYNCED" | "SYNCING" | "SYNCED" | "FAILED";
        lastGitSyncedAt: string | null;
        gitCommitCount: number;
        gitCurrentBranch: string | null;
        gitHeadHash: string | null;
        gitSyncError: string | null;
        createdAt: string;
        updatedAt: string;
    } | null>;
    progress: import("vue").Ref<{
        status: string;
        percentage: number;
        message?: string | undefined;
    } | null, {
        status: string;
        percentage: number;
        message?: string;
    } | {
        status: string;
        percentage: number;
        message?: string | undefined;
    } | null>;
    error: import("vue").Ref<string | null, string | null>;
    loading: import("vue").Ref<boolean, boolean>;
    load: (id: string, search?: string) => Promise<void>;
    sync: (id: string) => Promise<void>;
    open: (p: string, id: string) => Promise<void>;
    stop: () => void;
}, "progress" | "error" | "commits" | "selected" | "files" | "project" | "loading">, Pick<{
    commits: import("vue").Ref<{
        id: string;
        hash: string;
        shortHash: string;
        authorName: string;
        authorEmail: string | null;
        authoredAt: string;
        committerName: string | null;
        committerEmail: string | null;
        committedAt: string;
        subject: string;
        body: string | null;
        parentHashes: string[];
        branchNames: string[];
        tagNames: string[];
        filesChanged: number;
        insertions: number;
        deletions: number;
    }[], GitCommit[] | {
        id: string;
        hash: string;
        shortHash: string;
        authorName: string;
        authorEmail: string | null;
        authoredAt: string;
        committerName: string | null;
        committerEmail: string | null;
        committedAt: string;
        subject: string;
        body: string | null;
        parentHashes: string[];
        branchNames: string[];
        tagNames: string[];
        filesChanged: number;
        insertions: number;
        deletions: number;
    }[]>;
    selected: import("vue").Ref<{
        id: string;
        hash: string;
        shortHash: string;
        authorName: string;
        authorEmail: string | null;
        authoredAt: string;
        committerName: string | null;
        committerEmail: string | null;
        committedAt: string;
        subject: string;
        body: string | null;
        parentHashes: string[];
        branchNames: string[];
        tagNames: string[];
        filesChanged: number;
        insertions: number;
        deletions: number;
    } | null, GitCommit | {
        id: string;
        hash: string;
        shortHash: string;
        authorName: string;
        authorEmail: string | null;
        authoredAt: string;
        committerName: string | null;
        committerEmail: string | null;
        committedAt: string;
        subject: string;
        body: string | null;
        parentHashes: string[];
        branchNames: string[];
        tagNames: string[];
        filesChanged: number;
        insertions: number;
        deletions: number;
    } | null>;
    files: import("vue").Ref<{
        id: string;
        relativePath: string;
        previousPath: string | null;
        changeType: string;
        insertions: number | null;
        deletions: number | null;
    }[], GitCommitFile[] | {
        id: string;
        relativePath: string;
        previousPath: string | null;
        changeType: string;
        insertions: number | null;
        deletions: number | null;
    }[]>;
    project: import("vue").Ref<{
        id: string;
        name: string;
        path: string;
        framework: string | null;
        language: string | null;
        hasGit: boolean;
        indexStatus: import("@developer-memory/shared-types").ProjectIndexStatus;
        lastIndexedAt: string | null;
        indexedFileCount: number;
        indexError: string | null;
        gitSyncStatus: "NOT_SYNCED" | "SYNCING" | "SYNCED" | "FAILED";
        lastGitSyncedAt: string | null;
        gitCommitCount: number;
        gitCurrentBranch: string | null;
        gitHeadHash: string | null;
        gitSyncError: string | null;
        createdAt: string;
        updatedAt: string;
    } | null, Project | {
        id: string;
        name: string;
        path: string;
        framework: string | null;
        language: string | null;
        hasGit: boolean;
        indexStatus: import("@developer-memory/shared-types").ProjectIndexStatus;
        lastIndexedAt: string | null;
        indexedFileCount: number;
        indexError: string | null;
        gitSyncStatus: "NOT_SYNCED" | "SYNCING" | "SYNCED" | "FAILED";
        lastGitSyncedAt: string | null;
        gitCommitCount: number;
        gitCurrentBranch: string | null;
        gitHeadHash: string | null;
        gitSyncError: string | null;
        createdAt: string;
        updatedAt: string;
    } | null>;
    progress: import("vue").Ref<{
        status: string;
        percentage: number;
        message?: string | undefined;
    } | null, {
        status: string;
        percentage: number;
        message?: string;
    } | {
        status: string;
        percentage: number;
        message?: string | undefined;
    } | null>;
    error: import("vue").Ref<string | null, string | null>;
    loading: import("vue").Ref<boolean, boolean>;
    load: (id: string, search?: string) => Promise<void>;
    sync: (id: string) => Promise<void>;
    open: (p: string, id: string) => Promise<void>;
    stop: () => void;
}, never>, Pick<{
    commits: import("vue").Ref<{
        id: string;
        hash: string;
        shortHash: string;
        authorName: string;
        authorEmail: string | null;
        authoredAt: string;
        committerName: string | null;
        committerEmail: string | null;
        committedAt: string;
        subject: string;
        body: string | null;
        parentHashes: string[];
        branchNames: string[];
        tagNames: string[];
        filesChanged: number;
        insertions: number;
        deletions: number;
    }[], GitCommit[] | {
        id: string;
        hash: string;
        shortHash: string;
        authorName: string;
        authorEmail: string | null;
        authoredAt: string;
        committerName: string | null;
        committerEmail: string | null;
        committedAt: string;
        subject: string;
        body: string | null;
        parentHashes: string[];
        branchNames: string[];
        tagNames: string[];
        filesChanged: number;
        insertions: number;
        deletions: number;
    }[]>;
    selected: import("vue").Ref<{
        id: string;
        hash: string;
        shortHash: string;
        authorName: string;
        authorEmail: string | null;
        authoredAt: string;
        committerName: string | null;
        committerEmail: string | null;
        committedAt: string;
        subject: string;
        body: string | null;
        parentHashes: string[];
        branchNames: string[];
        tagNames: string[];
        filesChanged: number;
        insertions: number;
        deletions: number;
    } | null, GitCommit | {
        id: string;
        hash: string;
        shortHash: string;
        authorName: string;
        authorEmail: string | null;
        authoredAt: string;
        committerName: string | null;
        committerEmail: string | null;
        committedAt: string;
        subject: string;
        body: string | null;
        parentHashes: string[];
        branchNames: string[];
        tagNames: string[];
        filesChanged: number;
        insertions: number;
        deletions: number;
    } | null>;
    files: import("vue").Ref<{
        id: string;
        relativePath: string;
        previousPath: string | null;
        changeType: string;
        insertions: number | null;
        deletions: number | null;
    }[], GitCommitFile[] | {
        id: string;
        relativePath: string;
        previousPath: string | null;
        changeType: string;
        insertions: number | null;
        deletions: number | null;
    }[]>;
    project: import("vue").Ref<{
        id: string;
        name: string;
        path: string;
        framework: string | null;
        language: string | null;
        hasGit: boolean;
        indexStatus: import("@developer-memory/shared-types").ProjectIndexStatus;
        lastIndexedAt: string | null;
        indexedFileCount: number;
        indexError: string | null;
        gitSyncStatus: "NOT_SYNCED" | "SYNCING" | "SYNCED" | "FAILED";
        lastGitSyncedAt: string | null;
        gitCommitCount: number;
        gitCurrentBranch: string | null;
        gitHeadHash: string | null;
        gitSyncError: string | null;
        createdAt: string;
        updatedAt: string;
    } | null, Project | {
        id: string;
        name: string;
        path: string;
        framework: string | null;
        language: string | null;
        hasGit: boolean;
        indexStatus: import("@developer-memory/shared-types").ProjectIndexStatus;
        lastIndexedAt: string | null;
        indexedFileCount: number;
        indexError: string | null;
        gitSyncStatus: "NOT_SYNCED" | "SYNCING" | "SYNCED" | "FAILED";
        lastGitSyncedAt: string | null;
        gitCommitCount: number;
        gitCurrentBranch: string | null;
        gitHeadHash: string | null;
        gitSyncError: string | null;
        createdAt: string;
        updatedAt: string;
    } | null>;
    progress: import("vue").Ref<{
        status: string;
        percentage: number;
        message?: string | undefined;
    } | null, {
        status: string;
        percentage: number;
        message?: string;
    } | {
        status: string;
        percentage: number;
        message?: string | undefined;
    } | null>;
    error: import("vue").Ref<string | null, string | null>;
    loading: import("vue").Ref<boolean, boolean>;
    load: (id: string, search?: string) => Promise<void>;
    sync: (id: string) => Promise<void>;
    open: (p: string, id: string) => Promise<void>;
    stop: () => void;
}, "stop" | "load" | "sync" | "open">>;
