import type { IndexedFile, IndexedFileDetail, IndexProgress, IndexResult, Project } from '@developer-memory/shared-types';
export declare const useIndexingStore: import("pinia").StoreDefinition<"indexing", Pick<{
    project: import("vue").Ref<{
        id: string;
        name: string;
        path: string;
        framework: string | null;
        language: string | null;
        hasGit: boolean;
        indexStatus: import("@developer-memory/shared-types").ProjectIndexStatus;
        lastIndexedAt: string | null;
        indexedFileCount: number;
        indexError: string | null;
        gitSyncStatus: "NOT_SYNCED" | "SYNCING" | "SYNCED" | "FAILED";
        lastGitSyncedAt: string | null;
        gitCommitCount: number;
        gitCurrentBranch: string | null;
        gitHeadHash: string | null;
        gitSyncError: string | null;
        createdAt: string;
        updatedAt: string;
    } | null, Project | {
        id: string;
        name: string;
        path: string;
        framework: string | null;
        language: string | null;
        hasGit: boolean;
        indexStatus: import("@developer-memory/shared-types").ProjectIndexStatus;
        lastIndexedAt: string | null;
        indexedFileCount: number;
        indexError: string | null;
        gitSyncStatus: "NOT_SYNCED" | "SYNCING" | "SYNCED" | "FAILED";
        lastGitSyncedAt: string | null;
        gitCommitCount: number;
        gitCurrentBranch: string | null;
        gitHeadHash: string | null;
        gitSyncError: string | null;
        createdAt: string;
        updatedAt: string;
    } | null>;
    progress: import("vue").Ref<{
        projectId: string;
        status: import("@developer-memory/shared-types").IndexProgressStatus;
        currentFile?: string | undefined;
        processedFiles: number;
        totalFiles: number;
        percentage: number;
        message?: string | undefined;
    } | null, IndexProgress | {
        projectId: string;
        status: import("@developer-memory/shared-types").IndexProgressStatus;
        currentFile?: string | undefined;
        processedFiles: number;
        totalFiles: number;
        percentage: number;
        message?: string | undefined;
    } | null>;
    result: import("vue").Ref<{
        projectId: string;
        status: import("@developer-memory/shared-types").ProjectIndexStatus;
        scannedFiles: number;
        indexedFiles: number;
        updatedFiles: number;
        unchangedFiles: number;
        deletedFiles: number;
        skippedFiles: number;
        durationMs: number;
    } | null, IndexResult | {
        projectId: string;
        status: import("@developer-memory/shared-types").ProjectIndexStatus;
        scannedFiles: number;
        indexedFiles: number;
        updatedFiles: number;
        unchangedFiles: number;
        deletedFiles: number;
        skippedFiles: number;
        durationMs: number;
    } | null>;
    files: import("vue").Ref<{
        id: string;
        projectId: string;
        relativePath: string;
        extension: string | null;
        language: string | null;
        sizeBytes: number;
        lineCount: number;
        isBinary: boolean;
        indexedAt: string;
    }[], IndexedFile[] | {
        id: string;
        projectId: string;
        relativePath: string;
        extension: string | null;
        language: string | null;
        sizeBytes: number;
        lineCount: number;
        isBinary: boolean;
        indexedAt: string;
    }[]>;
    selectedFile: import("vue").Ref<{
        content: string | null;
        id: string;
        projectId: string;
        relativePath: string;
        extension: string | null;
        language: string | null;
        sizeBytes: number;
        lineCount: number;
        isBinary: boolean;
        indexedAt: string;
    } | null, IndexedFileDetail | {
        content: string | null;
        id: string;
        projectId: string;
        relativePath: string;
        extension: string | null;
        language: string | null;
        sizeBytes: number;
        lineCount: number;
        isBinary: boolean;
        indexedAt: string;
    } | null>;
    search: import("vue").Ref<string, string>;
    language: import("vue").Ref<string, string>;
    loading: import("vue").Ref<boolean, boolean>;
    error: import("vue").Ref<string | null, string | null>;
    isIndexing: import("vue").ComputedRef<boolean>;
    languages: import("vue").ComputedRef<string[]>;
    filteredFiles: import("vue").ComputedRef<{
        id: string;
        projectId: string;
        relativePath: string;
        extension: string | null;
        language: string | null;
        sizeBytes: number;
        lineCount: number;
        isBinary: boolean;
        indexedAt: string;
    }[]>;
    load: (projectId: string) => Promise<void>;
    start: (projectId: string) => Promise<void>;
    clear: (projectId: string) => Promise<void>;
    openFile: (projectId: string, fileId: string) => Promise<void>;
    stopPolling: () => void;
    reset: () => void;
}, "error" | "progress" | "search" | "project" | "language" | "files" | "loading" | "result" | "selectedFile">, Pick<{
    project: import("vue").Ref<{
        id: string;
        name: string;
        path: string;
        framework: string | null;
        language: string | null;
        hasGit: boolean;
        indexStatus: import("@developer-memory/shared-types").ProjectIndexStatus;
        lastIndexedAt: string | null;
        indexedFileCount: number;
        indexError: string | null;
        gitSyncStatus: "NOT_SYNCED" | "SYNCING" | "SYNCED" | "FAILED";
        lastGitSyncedAt: string | null;
        gitCommitCount: number;
        gitCurrentBranch: string | null;
        gitHeadHash: string | null;
        gitSyncError: string | null;
        createdAt: string;
        updatedAt: string;
    } | null, Project | {
        id: string;
        name: string;
        path: string;
        framework: string | null;
        language: string | null;
        hasGit: boolean;
        indexStatus: import("@developer-memory/shared-types").ProjectIndexStatus;
        lastIndexedAt: string | null;
        indexedFileCount: number;
        indexError: string | null;
        gitSyncStatus: "NOT_SYNCED" | "SYNCING" | "SYNCED" | "FAILED";
        lastGitSyncedAt: string | null;
        gitCommitCount: number;
        gitCurrentBranch: string | null;
        gitHeadHash: string | null;
        gitSyncError: string | null;
        createdAt: string;
        updatedAt: string;
    } | null>;
    progress: import("vue").Ref<{
        projectId: string;
        status: import("@developer-memory/shared-types").IndexProgressStatus;
        currentFile?: string | undefined;
        processedFiles: number;
        totalFiles: number;
        percentage: number;
        message?: string | undefined;
    } | null, IndexProgress | {
        projectId: string;
        status: import("@developer-memory/shared-types").IndexProgressStatus;
        currentFile?: string | undefined;
        processedFiles: number;
        totalFiles: number;
        percentage: number;
        message?: string | undefined;
    } | null>;
    result: import("vue").Ref<{
        projectId: string;
        status: import("@developer-memory/shared-types").ProjectIndexStatus;
        scannedFiles: number;
        indexedFiles: number;
        updatedFiles: number;
        unchangedFiles: number;
        deletedFiles: number;
        skippedFiles: number;
        durationMs: number;
    } | null, IndexResult | {
        projectId: string;
        status: import("@developer-memory/shared-types").ProjectIndexStatus;
        scannedFiles: number;
        indexedFiles: number;
        updatedFiles: number;
        unchangedFiles: number;
        deletedFiles: number;
        skippedFiles: number;
        durationMs: number;
    } | null>;
    files: import("vue").Ref<{
        id: string;
        projectId: string;
        relativePath: string;
        extension: string | null;
        language: string | null;
        sizeBytes: number;
        lineCount: number;
        isBinary: boolean;
        indexedAt: string;
    }[], IndexedFile[] | {
        id: string;
        projectId: string;
        relativePath: string;
        extension: string | null;
        language: string | null;
        sizeBytes: number;
        lineCount: number;
        isBinary: boolean;
        indexedAt: string;
    }[]>;
    selectedFile: import("vue").Ref<{
        content: string | null;
        id: string;
        projectId: string;
        relativePath: string;
        extension: string | null;
        language: string | null;
        sizeBytes: number;
        lineCount: number;
        isBinary: boolean;
        indexedAt: string;
    } | null, IndexedFileDetail | {
        content: string | null;
        id: string;
        projectId: string;
        relativePath: string;
        extension: string | null;
        language: string | null;
        sizeBytes: number;
        lineCount: number;
        isBinary: boolean;
        indexedAt: string;
    } | null>;
    search: import("vue").Ref<string, string>;
    language: import("vue").Ref<string, string>;
    loading: import("vue").Ref<boolean, boolean>;
    error: import("vue").Ref<string | null, string | null>;
    isIndexing: import("vue").ComputedRef<boolean>;
    languages: import("vue").ComputedRef<string[]>;
    filteredFiles: import("vue").ComputedRef<{
        id: string;
        projectId: string;
        relativePath: string;
        extension: string | null;
        language: string | null;
        sizeBytes: number;
        lineCount: number;
        isBinary: boolean;
        indexedAt: string;
    }[]>;
    load: (projectId: string) => Promise<void>;
    start: (projectId: string) => Promise<void>;
    clear: (projectId: string) => Promise<void>;
    openFile: (projectId: string, fileId: string) => Promise<void>;
    stopPolling: () => void;
    reset: () => void;
}, "isIndexing" | "languages" | "filteredFiles">, Pick<{
    project: import("vue").Ref<{
        id: string;
        name: string;
        path: string;
        framework: string | null;
        language: string | null;
        hasGit: boolean;
        indexStatus: import("@developer-memory/shared-types").ProjectIndexStatus;
        lastIndexedAt: string | null;
        indexedFileCount: number;
        indexError: string | null;
        gitSyncStatus: "NOT_SYNCED" | "SYNCING" | "SYNCED" | "FAILED";
        lastGitSyncedAt: string | null;
        gitCommitCount: number;
        gitCurrentBranch: string | null;
        gitHeadHash: string | null;
        gitSyncError: string | null;
        createdAt: string;
        updatedAt: string;
    } | null, Project | {
        id: string;
        name: string;
        path: string;
        framework: string | null;
        language: string | null;
        hasGit: boolean;
        indexStatus: import("@developer-memory/shared-types").ProjectIndexStatus;
        lastIndexedAt: string | null;
        indexedFileCount: number;
        indexError: string | null;
        gitSyncStatus: "NOT_SYNCED" | "SYNCING" | "SYNCED" | "FAILED";
        lastGitSyncedAt: string | null;
        gitCommitCount: number;
        gitCurrentBranch: string | null;
        gitHeadHash: string | null;
        gitSyncError: string | null;
        createdAt: string;
        updatedAt: string;
    } | null>;
    progress: import("vue").Ref<{
        projectId: string;
        status: import("@developer-memory/shared-types").IndexProgressStatus;
        currentFile?: string | undefined;
        processedFiles: number;
        totalFiles: number;
        percentage: number;
        message?: string | undefined;
    } | null, IndexProgress | {
        projectId: string;
        status: import("@developer-memory/shared-types").IndexProgressStatus;
        currentFile?: string | undefined;
        processedFiles: number;
        totalFiles: number;
        percentage: number;
        message?: string | undefined;
    } | null>;
    result: import("vue").Ref<{
        projectId: string;
        status: import("@developer-memory/shared-types").ProjectIndexStatus;
        scannedFiles: number;
        indexedFiles: number;
        updatedFiles: number;
        unchangedFiles: number;
        deletedFiles: number;
        skippedFiles: number;
        durationMs: number;
    } | null, IndexResult | {
        projectId: string;
        status: import("@developer-memory/shared-types").ProjectIndexStatus;
        scannedFiles: number;
        indexedFiles: number;
        updatedFiles: number;
        unchangedFiles: number;
        deletedFiles: number;
        skippedFiles: number;
        durationMs: number;
    } | null>;
    files: import("vue").Ref<{
        id: string;
        projectId: string;
        relativePath: string;
        extension: string | null;
        language: string | null;
        sizeBytes: number;
        lineCount: number;
        isBinary: boolean;
        indexedAt: string;
    }[], IndexedFile[] | {
        id: string;
        projectId: string;
        relativePath: string;
        extension: string | null;
        language: string | null;
        sizeBytes: number;
        lineCount: number;
        isBinary: boolean;
        indexedAt: string;
    }[]>;
    selectedFile: import("vue").Ref<{
        content: string | null;
        id: string;
        projectId: string;
        relativePath: string;
        extension: string | null;
        language: string | null;
        sizeBytes: number;
        lineCount: number;
        isBinary: boolean;
        indexedAt: string;
    } | null, IndexedFileDetail | {
        content: string | null;
        id: string;
        projectId: string;
        relativePath: string;
        extension: string | null;
        language: string | null;
        sizeBytes: number;
        lineCount: number;
        isBinary: boolean;
        indexedAt: string;
    } | null>;
    search: import("vue").Ref<string, string>;
    language: import("vue").Ref<string, string>;
    loading: import("vue").Ref<boolean, boolean>;
    error: import("vue").Ref<string | null, string | null>;
    isIndexing: import("vue").ComputedRef<boolean>;
    languages: import("vue").ComputedRef<string[]>;
    filteredFiles: import("vue").ComputedRef<{
        id: string;
        projectId: string;
        relativePath: string;
        extension: string | null;
        language: string | null;
        sizeBytes: number;
        lineCount: number;
        isBinary: boolean;
        indexedAt: string;
    }[]>;
    load: (projectId: string) => Promise<void>;
    start: (projectId: string) => Promise<void>;
    clear: (projectId: string) => Promise<void>;
    openFile: (projectId: string, fileId: string) => Promise<void>;
    stopPolling: () => void;
    reset: () => void;
}, "load" | "reset" | "clear" | "start" | "openFile" | "stopPolling">>;
