import type { MemoryEntry } from '@developer-memory/shared-types';
export declare const useMemoriesStore: import("pinia").StoreDefinition<"memories", Pick<{
    items: import("vue").Ref<{
        id: string;
        projectId: string;
        sessionId: string | null;
        type: "NOTE" | "DECISION" | "BUG" | "TASK" | "SOLUTION" | "QUESTION" | "OUTCOME";
        title: string;
        content: string;
        status: "OPEN" | "RESOLVED" | "ARCHIVED";
        priority: "LOW" | "MEDIUM" | "HIGH" | null;
        commitHash: string | null;
        relativeFilePath: string | null;
        lineStart: number | null;
        lineEnd: number | null;
        tags: string[];
        createdAt: string;
        updatedAt: string;
        resolvedAt: string | null;
        session?: {
            id: string;
            projectId: string;
            title: string;
            summary: string | null;
            status: "ACTIVE" | "COMPLETED" | "PAUSED";
            startedAt: string;
            endedAt: string | null;
            durationMinutes: number | null;
            branchName: string | null;
            baseCommitHash: string | null;
            headCommitHash: string | null;
            memories?: /*elided*/ any[] | undefined;
        } | null | undefined;
    }[], MemoryEntry[] | {
        id: string;
        projectId: string;
        sessionId: string | null;
        type: "NOTE" | "DECISION" | "BUG" | "TASK" | "SOLUTION" | "QUESTION" | "OUTCOME";
        title: string;
        content: string;
        status: "OPEN" | "RESOLVED" | "ARCHIVED";
        priority: "LOW" | "MEDIUM" | "HIGH" | null;
        commitHash: string | null;
        relativeFilePath: string | null;
        lineStart: number | null;
        lineEnd: number | null;
        tags: string[];
        createdAt: string;
        updatedAt: string;
        resolvedAt: string | null;
        session?: {
            id: string;
            projectId: string;
            title: string;
            summary: string | null;
            status: "ACTIVE" | "COMPLETED" | "PAUSED";
            startedAt: string;
            endedAt: string | null;
            durationMinutes: number | null;
            branchName: string | null;
            baseCommitHash: string | null;
            headCommitHash: string | null;
            memories?: /*elided*/ any[] | undefined;
        } | null | undefined;
    }[]>;
    error: import("vue").Ref<string | null, string | null>;
    load: (p: string) => Promise<void>;
    create: (p: string, input: Partial<MemoryEntry> & Pick<MemoryEntry, "type" | "title" | "content">) => Promise<void>;
    action: (p: string, id: string, a: "resolve" | "archive") => Promise<void>;
}, "items" | "error">, Pick<{
    items: import("vue").Ref<{
        id: string;
        projectId: string;
        sessionId: string | null;
        type: "NOTE" | "DECISION" | "BUG" | "TASK" | "SOLUTION" | "QUESTION" | "OUTCOME";
        title: string;
        content: string;
        status: "OPEN" | "RESOLVED" | "ARCHIVED";
        priority: "LOW" | "MEDIUM" | "HIGH" | null;
        commitHash: string | null;
        relativeFilePath: string | null;
        lineStart: number | null;
        lineEnd: number | null;
        tags: string[];
        createdAt: string;
        updatedAt: string;
        resolvedAt: string | null;
        session?: {
            id: string;
            projectId: string;
            title: string;
            summary: string | null;
            status: "ACTIVE" | "COMPLETED" | "PAUSED";
            startedAt: string;
            endedAt: string | null;
            durationMinutes: number | null;
            branchName: string | null;
            baseCommitHash: string | null;
            headCommitHash: string | null;
            memories?: /*elided*/ any[] | undefined;
        } | null | undefined;
    }[], MemoryEntry[] | {
        id: string;
        projectId: string;
        sessionId: string | null;
        type: "NOTE" | "DECISION" | "BUG" | "TASK" | "SOLUTION" | "QUESTION" | "OUTCOME";
        title: string;
        content: string;
        status: "OPEN" | "RESOLVED" | "ARCHIVED";
        priority: "LOW" | "MEDIUM" | "HIGH" | null;
        commitHash: string | null;
        relativeFilePath: string | null;
        lineStart: number | null;
        lineEnd: number | null;
        tags: string[];
        createdAt: string;
        updatedAt: string;
        resolvedAt: string | null;
        session?: {
            id: string;
            projectId: string;
            title: string;
            summary: string | null;
            status: "ACTIVE" | "COMPLETED" | "PAUSED";
            startedAt: string;
            endedAt: string | null;
            durationMinutes: number | null;
            branchName: string | null;
            baseCommitHash: string | null;
            headCommitHash: string | null;
            memories?: /*elided*/ any[] | undefined;
        } | null | undefined;
    }[]>;
    error: import("vue").Ref<string | null, string | null>;
    load: (p: string) => Promise<void>;
    create: (p: string, input: Partial<MemoryEntry> & Pick<MemoryEntry, "type" | "title" | "content">) => Promise<void>;
    action: (p: string, id: string, a: "resolve" | "archive") => Promise<void>;
}, never>, Pick<{
    items: import("vue").Ref<{
        id: string;
        projectId: string;
        sessionId: string | null;
        type: "NOTE" | "DECISION" | "BUG" | "TASK" | "SOLUTION" | "QUESTION" | "OUTCOME";
        title: string;
        content: string;
        status: "OPEN" | "RESOLVED" | "ARCHIVED";
        priority: "LOW" | "MEDIUM" | "HIGH" | null;
        commitHash: string | null;
        relativeFilePath: string | null;
        lineStart: number | null;
        lineEnd: number | null;
        tags: string[];
        createdAt: string;
        updatedAt: string;
        resolvedAt: string | null;
        session?: {
            id: string;
            projectId: string;
            title: string;
            summary: string | null;
            status: "ACTIVE" | "COMPLETED" | "PAUSED";
            startedAt: string;
            endedAt: string | null;
            durationMinutes: number | null;
            branchName: string | null;
            baseCommitHash: string | null;
            headCommitHash: string | null;
            memories?: /*elided*/ any[] | undefined;
        } | null | undefined;
    }[], MemoryEntry[] | {
        id: string;
        projectId: string;
        sessionId: string | null;
        type: "NOTE" | "DECISION" | "BUG" | "TASK" | "SOLUTION" | "QUESTION" | "OUTCOME";
        title: string;
        content: string;
        status: "OPEN" | "RESOLVED" | "ARCHIVED";
        priority: "LOW" | "MEDIUM" | "HIGH" | null;
        commitHash: string | null;
        relativeFilePath: string | null;
        lineStart: number | null;
        lineEnd: number | null;
        tags: string[];
        createdAt: string;
        updatedAt: string;
        resolvedAt: string | null;
        session?: {
            id: string;
            projectId: string;
            title: string;
            summary: string | null;
            status: "ACTIVE" | "COMPLETED" | "PAUSED";
            startedAt: string;
            endedAt: string | null;
            durationMinutes: number | null;
            branchName: string | null;
            baseCommitHash: string | null;
            headCommitHash: string | null;
            memories?: /*elided*/ any[] | undefined;
        } | null | undefined;
    }[]>;
    error: import("vue").Ref<string | null, string | null>;
    load: (p: string) => Promise<void>;
    create: (p: string, input: Partial<MemoryEntry> & Pick<MemoryEntry, "type" | "title" | "content">) => Promise<void>;
    action: (p: string, id: string, a: "resolve" | "archive") => Promise<void>;
}, "load" | "create" | "action">>;
