import type { CreateProjectInput, Project } from '@developer-memory/shared-types';
export declare const useProjectsStore: import("pinia").StoreDefinition<"projects", Pick<{
    projects: import("vue").Ref<{
        id: string;
        name: string;
        path: string;
        framework: string | null;
        language: string | null;
        hasGit: boolean;
        indexStatus: import("@developer-memory/shared-types").ProjectIndexStatus;
        lastIndexedAt: string | null;
        indexedFileCount: number;
        indexError: string | null;
        gitSyncStatus: "NOT_SYNCED" | "SYNCING" | "SYNCED" | "FAILED";
        lastGitSyncedAt: string | null;
        gitCommitCount: number;
        gitCurrentBranch: string | null;
        gitHeadHash: string | null;
        gitSyncError: string | null;
        createdAt: string;
        updatedAt: string;
    }[], Project[] | {
        id: string;
        name: string;
        path: string;
        framework: string | null;
        language: string | null;
        hasGit: boolean;
        indexStatus: import("@developer-memory/shared-types").ProjectIndexStatus;
        lastIndexedAt: string | null;
        indexedFileCount: number;
        indexError: string | null;
        gitSyncStatus: "NOT_SYNCED" | "SYNCING" | "SYNCED" | "FAILED";
        lastGitSyncedAt: string | null;
        gitCommitCount: number;
        gitCurrentBranch: string | null;
        gitHeadHash: string | null;
        gitSyncError: string | null;
        createdAt: string;
        updatedAt: string;
    }[]>;
    loading: import("vue").Ref<boolean, boolean>;
    error: import("vue").Ref<string | null, string | null>;
    hasProjects: import("vue").ComputedRef<boolean>;
    load: () => Promise<void>;
    create: (input: CreateProjectInput) => Promise<Project>;
    remove: (id: string) => Promise<void>;
}, "error" | "loading" | "projects">, Pick<{
    projects: import("vue").Ref<{
        id: string;
        name: string;
        path: string;
        framework: string | null;
        language: string | null;
        hasGit: boolean;
        indexStatus: import("@developer-memory/shared-types").ProjectIndexStatus;
        lastIndexedAt: string | null;
        indexedFileCount: number;
        indexError: string | null;
        gitSyncStatus: "NOT_SYNCED" | "SYNCING" | "SYNCED" | "FAILED";
        lastGitSyncedAt: string | null;
        gitCommitCount: number;
        gitCurrentBranch: string | null;
        gitHeadHash: string | null;
        gitSyncError: string | null;
        createdAt: string;
        updatedAt: string;
    }[], Project[] | {
        id: string;
        name: string;
        path: string;
        framework: string | null;
        language: string | null;
        hasGit: boolean;
        indexStatus: import("@developer-memory/shared-types").ProjectIndexStatus;
        lastIndexedAt: string | null;
        indexedFileCount: number;
        indexError: string | null;
        gitSyncStatus: "NOT_SYNCED" | "SYNCING" | "SYNCED" | "FAILED";
        lastGitSyncedAt: string | null;
        gitCommitCount: number;
        gitCurrentBranch: string | null;
        gitHeadHash: string | null;
        gitSyncError: string | null;
        createdAt: string;
        updatedAt: string;
    }[]>;
    loading: import("vue").Ref<boolean, boolean>;
    error: import("vue").Ref<string | null, string | null>;
    hasProjects: import("vue").ComputedRef<boolean>;
    load: () => Promise<void>;
    create: (input: CreateProjectInput) => Promise<Project>;
    remove: (id: string) => Promise<void>;
}, "hasProjects">, Pick<{
    projects: import("vue").Ref<{
        id: string;
        name: string;
        path: string;
        framework: string | null;
        language: string | null;
        hasGit: boolean;
        indexStatus: import("@developer-memory/shared-types").ProjectIndexStatus;
        lastIndexedAt: string | null;
        indexedFileCount: number;
        indexError: string | null;
        gitSyncStatus: "NOT_SYNCED" | "SYNCING" | "SYNCED" | "FAILED";
        lastGitSyncedAt: string | null;
        gitCommitCount: number;
        gitCurrentBranch: string | null;
        gitHeadHash: string | null;
        gitSyncError: string | null;
        createdAt: string;
        updatedAt: string;
    }[], Project[] | {
        id: string;
        name: string;
        path: string;
        framework: string | null;
        language: string | null;
        hasGit: boolean;
        indexStatus: import("@developer-memory/shared-types").ProjectIndexStatus;
        lastIndexedAt: string | null;
        indexedFileCount: number;
        indexError: string | null;
        gitSyncStatus: "NOT_SYNCED" | "SYNCING" | "SYNCED" | "FAILED";
        lastGitSyncedAt: string | null;
        gitCommitCount: number;
        gitCurrentBranch: string | null;
        gitHeadHash: string | null;
        gitSyncError: string | null;
        createdAt: string;
        updatedAt: string;
    }[]>;
    loading: import("vue").Ref<boolean, boolean>;
    error: import("vue").Ref<string | null, string | null>;
    hasProjects: import("vue").ComputedRef<boolean>;
    load: () => Promise<void>;
    create: (input: CreateProjectInput) => Promise<Project>;
    remove: (id: string) => Promise<void>;
}, "load" | "create" | "remove">>;
