import type { DevelopmentSession } from '@developer-memory/shared-types';
export declare const useSessionsStore: import("pinia").StoreDefinition<"sessions", Pick<{
    items: import("vue").Ref<{
        id: string;
        projectId: string;
        title: string;
        summary: string | null;
        status: "ACTIVE" | "COMPLETED" | "PAUSED";
        startedAt: string;
        endedAt: string | null;
        durationMinutes: number | null;
        branchName: string | null;
        baseCommitHash: string | null;
        headCommitHash: string | null;
        memories?: {
            id: string;
            projectId: string;
            sessionId: string | null;
            type: "NOTE" | "DECISION" | "BUG" | "TASK" | "SOLUTION" | "QUESTION" | "OUTCOME";
            title: string;
            content: string;
            status: "OPEN" | "RESOLVED" | "ARCHIVED";
            priority: "LOW" | "MEDIUM" | "HIGH" | null;
            commitHash: string | null;
            relativeFilePath: string | null;
            lineStart: number | null;
            lineEnd: number | null;
            tags: string[];
            createdAt: string;
            updatedAt: string;
            resolvedAt: string | null;
            session?: /*elided*/ any | null | undefined;
        }[] | undefined;
    }[], DevelopmentSession[] | {
        id: string;
        projectId: string;
        title: string;
        summary: string | null;
        status: "ACTIVE" | "COMPLETED" | "PAUSED";
        startedAt: string;
        endedAt: string | null;
        durationMinutes: number | null;
        branchName: string | null;
        baseCommitHash: string | null;
        headCommitHash: string | null;
        memories?: {
            id: string;
            projectId: string;
            sessionId: string | null;
            type: "NOTE" | "DECISION" | "BUG" | "TASK" | "SOLUTION" | "QUESTION" | "OUTCOME";
            title: string;
            content: string;
            status: "OPEN" | "RESOLVED" | "ARCHIVED";
            priority: "LOW" | "MEDIUM" | "HIGH" | null;
            commitHash: string | null;
            relativeFilePath: string | null;
            lineStart: number | null;
            lineEnd: number | null;
            tags: string[];
            createdAt: string;
            updatedAt: string;
            resolvedAt: string | null;
            session?: /*elided*/ any | null | undefined;
        }[] | undefined;
    }[]>;
    error: import("vue").Ref<string | null, string | null>;
    active: import("vue").ComputedRef<{
        id: string;
        projectId: string;
        title: string;
        summary: string | null;
        status: "ACTIVE" | "COMPLETED" | "PAUSED";
        startedAt: string;
        endedAt: string | null;
        durationMinutes: number | null;
        branchName: string | null;
        baseCommitHash: string | null;
        headCommitHash: string | null;
        memories?: {
            id: string;
            projectId: string;
            sessionId: string | null;
            type: "NOTE" | "DECISION" | "BUG" | "TASK" | "SOLUTION" | "QUESTION" | "OUTCOME";
            title: string;
            content: string;
            status: "OPEN" | "RESOLVED" | "ARCHIVED";
            priority: "LOW" | "MEDIUM" | "HIGH" | null;
            commitHash: string | null;
            relativeFilePath: string | null;
            lineStart: number | null;
            lineEnd: number | null;
            tags: string[];
            createdAt: string;
            updatedAt: string;
            resolvedAt: string | null;
            session?: /*elided*/ any | null | undefined;
        }[] | undefined;
    } | undefined>;
    load: (p: string) => Promise<void>;
    create: (p: string, title: string, summary: string) => Promise<void>;
    action: (p: string, id: string, a: "pause" | "resume" | "complete") => Promise<void>;
    remove: (p: string, id: string) => Promise<void>;
}, "items" | "error">, Pick<{
    items: import("vue").Ref<{
        id: string;
        projectId: string;
        title: string;
        summary: string | null;
        status: "ACTIVE" | "COMPLETED" | "PAUSED";
        startedAt: string;
        endedAt: string | null;
        durationMinutes: number | null;
        branchName: string | null;
        baseCommitHash: string | null;
        headCommitHash: string | null;
        memories?: {
            id: string;
            projectId: string;
            sessionId: string | null;
            type: "NOTE" | "DECISION" | "BUG" | "TASK" | "SOLUTION" | "QUESTION" | "OUTCOME";
            title: string;
            content: string;
            status: "OPEN" | "RESOLVED" | "ARCHIVED";
            priority: "LOW" | "MEDIUM" | "HIGH" | null;
            commitHash: string | null;
            relativeFilePath: string | null;
            lineStart: number | null;
            lineEnd: number | null;
            tags: string[];
            createdAt: string;
            updatedAt: string;
            resolvedAt: string | null;
            session?: /*elided*/ any | null | undefined;
        }[] | undefined;
    }[], DevelopmentSession[] | {
        id: string;
        projectId: string;
        title: string;
        summary: string | null;
        status: "ACTIVE" | "COMPLETED" | "PAUSED";
        startedAt: string;
        endedAt: string | null;
        durationMinutes: number | null;
        branchName: string | null;
        baseCommitHash: string | null;
        headCommitHash: string | null;
        memories?: {
            id: string;
            projectId: string;
            sessionId: string | null;
            type: "NOTE" | "DECISION" | "BUG" | "TASK" | "SOLUTION" | "QUESTION" | "OUTCOME";
            title: string;
            content: string;
            status: "OPEN" | "RESOLVED" | "ARCHIVED";
            priority: "LOW" | "MEDIUM" | "HIGH" | null;
            commitHash: string | null;
            relativeFilePath: string | null;
            lineStart: number | null;
            lineEnd: number | null;
            tags: string[];
            createdAt: string;
            updatedAt: string;
            resolvedAt: string | null;
            session?: /*elided*/ any | null | undefined;
        }[] | undefined;
    }[]>;
    error: import("vue").Ref<string | null, string | null>;
    active: import("vue").ComputedRef<{
        id: string;
        projectId: string;
        title: string;
        summary: string | null;
        status: "ACTIVE" | "COMPLETED" | "PAUSED";
        startedAt: string;
        endedAt: string | null;
        durationMinutes: number | null;
        branchName: string | null;
        baseCommitHash: string | null;
        headCommitHash: string | null;
        memories?: {
            id: string;
            projectId: string;
            sessionId: string | null;
            type: "NOTE" | "DECISION" | "BUG" | "TASK" | "SOLUTION" | "QUESTION" | "OUTCOME";
            title: string;
            content: string;
            status: "OPEN" | "RESOLVED" | "ARCHIVED";
            priority: "LOW" | "MEDIUM" | "HIGH" | null;
            commitHash: string | null;
            relativeFilePath: string | null;
            lineStart: number | null;
            lineEnd: number | null;
            tags: string[];
            createdAt: string;
            updatedAt: string;
            resolvedAt: string | null;
            session?: /*elided*/ any | null | undefined;
        }[] | undefined;
    } | undefined>;
    load: (p: string) => Promise<void>;
    create: (p: string, title: string, summary: string) => Promise<void>;
    action: (p: string, id: string, a: "pause" | "resume" | "complete") => Promise<void>;
    remove: (p: string, id: string) => Promise<void>;
}, "active">, Pick<{
    items: import("vue").Ref<{
        id: string;
        projectId: string;
        title: string;
        summary: string | null;
        status: "ACTIVE" | "COMPLETED" | "PAUSED";
        startedAt: string;
        endedAt: string | null;
        durationMinutes: number | null;
        branchName: string | null;
        baseCommitHash: string | null;
        headCommitHash: string | null;
        memories?: {
            id: string;
            projectId: string;
            sessionId: string | null;
            type: "NOTE" | "DECISION" | "BUG" | "TASK" | "SOLUTION" | "QUESTION" | "OUTCOME";
            title: string;
            content: string;
            status: "OPEN" | "RESOLVED" | "ARCHIVED";
            priority: "LOW" | "MEDIUM" | "HIGH" | null;
            commitHash: string | null;
            relativeFilePath: string | null;
            lineStart: number | null;
            lineEnd: number | null;
            tags: string[];
            createdAt: string;
            updatedAt: string;
            resolvedAt: string | null;
            session?: /*elided*/ any | null | undefined;
        }[] | undefined;
    }[], DevelopmentSession[] | {
        id: string;
        projectId: string;
        title: string;
        summary: string | null;
        status: "ACTIVE" | "COMPLETED" | "PAUSED";
        startedAt: string;
        endedAt: string | null;
        durationMinutes: number | null;
        branchName: string | null;
        baseCommitHash: string | null;
        headCommitHash: string | null;
        memories?: {
            id: string;
            projectId: string;
            sessionId: string | null;
            type: "NOTE" | "DECISION" | "BUG" | "TASK" | "SOLUTION" | "QUESTION" | "OUTCOME";
            title: string;
            content: string;
            status: "OPEN" | "RESOLVED" | "ARCHIVED";
            priority: "LOW" | "MEDIUM" | "HIGH" | null;
            commitHash: string | null;
            relativeFilePath: string | null;
            lineStart: number | null;
            lineEnd: number | null;
            tags: string[];
            createdAt: string;
            updatedAt: string;
            resolvedAt: string | null;
            session?: /*elided*/ any | null | undefined;
        }[] | undefined;
    }[]>;
    error: import("vue").Ref<string | null, string | null>;
    active: import("vue").ComputedRef<{
        id: string;
        projectId: string;
        title: string;
        summary: string | null;
        status: "ACTIVE" | "COMPLETED" | "PAUSED";
        startedAt: string;
        endedAt: string | null;
        durationMinutes: number | null;
        branchName: string | null;
        baseCommitHash: string | null;
        headCommitHash: string | null;
        memories?: {
            id: string;
            projectId: string;
            sessionId: string | null;
            type: "NOTE" | "DECISION" | "BUG" | "TASK" | "SOLUTION" | "QUESTION" | "OUTCOME";
            title: string;
            content: string;
            status: "OPEN" | "RESOLVED" | "ARCHIVED";
            priority: "LOW" | "MEDIUM" | "HIGH" | null;
            commitHash: string | null;
            relativeFilePath: string | null;
            lineStart: number | null;
            lineEnd: number | null;
            tags: string[];
            createdAt: string;
            updatedAt: string;
            resolvedAt: string | null;
            session?: /*elided*/ any | null | undefined;
        }[] | undefined;
    } | undefined>;
    load: (p: string) => Promise<void>;
    create: (p: string, title: string, summary: string) => Promise<void>;
    action: (p: string, id: string, a: "pause" | "resume" | "complete") => Promise<void>;
    remove: (p: string, id: string) => Promise<void>;
}, "load" | "create" | "action" | "remove">>;
