import{ConflictException,Injectable,NotFoundException}from'@nestjs/common';import{InjectRepository}from'@nestjs/typeorm';import{Repository}from'typeorm';import{Project}from'../projects/project.entity';import{GitCommandService}from'../git/git-command.service';import{DevelopmentSession,SessionStatus}from'./development-session.entity';import{SessionRepositoryService}from'./session-repository.service';import type{CreateSessionDto,UpdateSessionDto}from'./dto/session.dto';
export function calculateDurationMinutes(startedAt:Date,endedAt:Date):number{return Math.max(0,Math.round((endedAt.getTime()-startedAt.getTime())/60000))}
@Injectable()export class SessionsService{constructor(@InjectRepository(Project)private readonly projects:Repository<Project>,private readonly sessions:SessionRepositoryService,private readonly git:GitCommandService){}
 async create(projectId:string,input:CreateSessionDto){const project=await this.project(projectId);if(await this.sessions.active(projectId))throw new ConflictException('An active session already exists for this project');let branch=input.branchName??null,head:string|null=null;try{await this.git.validateRepository(project.path);branch=branch??((await this.git.branch(project.path))||null);head=await this.git.head(project.path)}catch{}try{return await this.sessions.repository.save(this.sessions.repository.create({projectId,...input,summary:input.summary??null,branchName:branch,baseCommitHash:head,headCommitHash:null,status:SessionStatus.ACTIVE,startedAt:new Date(),endedAt:null,durationMinutes:null}))}catch{throw new ConflictException('An active session already exists for this project')}}
 list(projectId:string){return this.project(projectId).then(()=>this.sessions.list(projectId))}async one(projectId:string,id:string){const value=await this.sessions.one(projectId,id);if(!value)throw new NotFoundException('Session was not found');return value}
 async update(projectId:string,id:string,input:UpdateSessionDto){const value=await this.one(projectId,id);Object.assign(value,input);return this.sessions.repository.save(value)}
 async complete(projectId:string,id:string){const value=await this.one(projectId,id);const project=await this.project(projectId);let head=value.headCommitHash;try{head=await this.git.head(project.path)}catch{}const endedAt=new Date();Object.assign(value,{status:SessionStatus.COMPLETED,endedAt,headCommitHash:head,durationMinutes:calculateDurationMinutes(value.startedAt,endedAt)});return this.sessions.repository.save(value)}
 async pause(projectId:string,id:string){const value=await this.one(projectId,id);if(value.status!==SessionStatus.ACTIVE)throw new ConflictException('Only an active session can be paused');value.status=SessionStatus.PAUSED;return this.sessions.repository.save(value)}
 async resume(projectId:string,id:string){const value=await this.one(projectId,id);if(await this.sessions.active(projectId))throw new ConflictException('An active session already exists for this project');value.status=SessionStatus.ACTIVE;value.endedAt=null;try{return await this.sessions.repository.save(value)}catch{throw new ConflictException('An active session already exists for this project')}}
 async remove(projectId:string,id:string){await this.one(projectId,id);await this.sessions.repository.delete(id)}
 private async project(id:string){const value=await this.projects.findOneBy({id});if(!value)throw new NotFoundException('Project was not found');return value}}
