import type{MigrationInterface,QueryRunner}from'typeorm';
export class AddGitSessionsMemories1721721600000 implements MigrationInterface{name='AddGitSessionsMemories1721721600000';async up(q:QueryRunner){
 await q.query(`ALTER TABLE projects ADD COLUMN gitSyncStatus text NOT NULL DEFAULT ('NOT_SYNCED')`);await q.query(`ALTER TABLE projects ADD COLUMN lastGitSyncedAt datetime`);await q.query(`ALTER TABLE projects ADD COLUMN gitCommitCount integer NOT NULL DEFAULT (0)`);await q.query(`ALTER TABLE projects ADD COLUMN gitCurrentBranch text`);await q.query(`ALTER TABLE projects ADD COLUMN gitHeadHash text`);await q.query(`ALTER TABLE projects ADD COLUMN gitSyncError text`);
 await q.query(`CREATE TABLE git_commits(id varchar PRIMARY KEY NOT NULL,projectId varchar NOT NULL,hash text NOT NULL,shortHash text NOT NULL,authorName text NOT NULL,authorEmail text,authoredAt datetime NOT NULL,committerName text,committerEmail text,committedAt datetime NOT NULL,subject text NOT NULL,body text,parentHashes text NOT NULL,branchNames text NOT NULL,tagNames text NOT NULL,filesChanged integer NOT NULL DEFAULT 0,insertions integer NOT NULL DEFAULT 0,deletions integer NOT NULL DEFAULT 0,createdAt datetime NOT NULL DEFAULT(datetime('now')),updatedAt datetime NOT NULL DEFAULT(datetime('now')),CONSTRAINT UQ_git_commits_project_hash UNIQUE(projectId,hash),FOREIGN KEY(projectId) REFERENCES projects(id) ON DELETE CASCADE)`);
 for(const sql of [`CREATE INDEX IDX_git_commits_project ON git_commits(projectId)`,`CREATE INDEX IDX_git_commits_authored ON git_commits(authoredAt)`,`CREATE INDEX IDX_git_commits_committed ON git_commits(committedAt)`,`CREATE INDEX IDX_git_commits_subject ON git_commits(subject)`])await q.query(sql);
 await q.query(`CREATE TABLE git_commit_files(id varchar PRIMARY KEY NOT NULL,commitId varchar NOT NULL,projectId varchar NOT NULL,relativePath text NOT NULL,previousPath text,changeType text NOT NULL DEFAULT 'UNKNOWN',insertions integer,deletions integer,createdAt datetime NOT NULL DEFAULT(datetime('now')),CONSTRAINT UQ_commit_file_path UNIQUE(commitId,relativePath,previousPath),FOREIGN KEY(commitId) REFERENCES git_commits(id) ON DELETE CASCADE)`);
 for(const sql of [`CREATE INDEX IDX_commit_files_commit ON git_commit_files(commitId)`,`CREATE INDEX IDX_commit_files_project ON git_commit_files(projectId)`,`CREATE INDEX IDX_commit_files_path ON git_commit_files(relativePath)`])await q.query(sql);
 await q.query(`CREATE TABLE development_sessions(id varchar PRIMARY KEY NOT NULL,projectId varchar NOT NULL,title varchar(200) NOT NULL,summary text,status text NOT NULL DEFAULT 'ACTIVE',startedAt datetime NOT NULL,endedAt datetime,durationMinutes integer,branchName text,baseCommitHash text,headCommitHash text,createdAt datetime NOT NULL DEFAULT(datetime('now')),updatedAt datetime NOT NULL DEFAULT(datetime('now')),FOREIGN KEY(projectId) REFERENCES projects(id) ON DELETE CASCADE)`);
 await q.query(`CREATE INDEX IDX_sessions_project ON development_sessions(projectId)`);await q.query(`CREATE INDEX IDX_sessions_status ON development_sessions(status)`);await q.query(`CREATE INDEX IDX_sessions_started ON development_sessions(startedAt)`);await q.query(`CREATE UNIQUE INDEX UQ_active_session_project ON development_sessions(projectId) WHERE status='ACTIVE'`);
 await q.query(`CREATE TABLE memory_entries(id varchar PRIMARY KEY NOT NULL,projectId varchar NOT NULL,sessionId varchar,type text NOT NULL,title varchar(200) NOT NULL,content text NOT NULL,status text NOT NULL DEFAULT 'OPEN',priority text,commitHash text,relativeFilePath text,lineStart integer,lineEnd integer,tags text NOT NULL,createdAt datetime NOT NULL DEFAULT(datetime('now')),updatedAt datetime NOT NULL DEFAULT(datetime('now')),resolvedAt datetime,FOREIGN KEY(projectId) REFERENCES projects(id) ON DELETE CASCADE,FOREIGN KEY(sessionId) REFERENCES development_sessions(id) ON DELETE SET NULL)`);
 for(const sql of [`CREATE INDEX IDX_memories_project ON memory_entries(projectId)`,`CREATE INDEX IDX_memories_session ON memory_entries(sessionId)`,`CREATE INDEX IDX_memories_type ON memory_entries(type)`,`CREATE INDEX IDX_memories_status ON memory_entries(status)`,`CREATE INDEX IDX_memories_commit ON memory_entries(commitHash)`,`CREATE INDEX IDX_memories_file ON memory_entries(relativeFilePath)`,`CREATE INDEX IDX_memories_created ON memory_entries(createdAt)`])await q.query(sql);
 }async down(q:QueryRunner){await q.query(`DROP TABLE memory_entries`);await q.query(`DROP TABLE development_sessions`);await q.query(`DROP TABLE git_commit_files`);await q.query(`DROP TABLE git_commits`);for(const column of['gitSyncError','gitHeadHash','gitCurrentBranch','gitCommitCount','lastGitSyncedAt','gitSyncStatus'])await q.query(`ALTER TABLE projects DROP COLUMN ${column}`)}}
