import{BadRequestException,Injectable,NotFoundException}from'@nestjs/common';import{InjectRepository}from'@nestjs/typeorm';import{Repository}from'typeorm';import{isAbsolute,normalize}from'node:path';import{Project}from'../projects/project.entity';import{DevelopmentSession}from'../sessions/development-session.entity';import{GitCommit}from'../git/git-commit.entity';import{MemoryEntry,MemoryStatus}from'./memory-entry.entity';import{MemoryRepositoryService}from'./memory-repository.service';import type{CreateMemoryDto,UpdateMemoryDto}from'./dto/memory.dto';
export function normalizeTags(tags:string[]=[]):string[]{const seen=new Set<string>();return tags.map(t=>t.trim()).filter(t=>{const key=t.toLowerCase();if(!t||seen.has(key))return false;seen.add(key);return true})}
export function validateLineRange(start?:number,end?:number):void{if(end!==undefined&&start===undefined)throw new BadRequestException('lineStart is required when lineEnd is provided');if(start!==undefined&&end!==undefined&&end<start)throw new BadRequestException('lineEnd must be greater than or equal to lineStart')}
@Injectable()export class MemoriesService{constructor(@InjectRepository(Project)private projects:Repository<Project>,@InjectRepository(DevelopmentSession)private sessions:Repository<DevelopmentSession>,@InjectRepository(GitCommit)private commits:Repository<GitCommit>,private memories:MemoryRepositoryService){}
 async create(projectId:string,input:CreateMemoryDto){await this.validate(projectId,input);return this.memories.repository.save(this.memories.repository.create({...input,projectId,sessionId:input.sessionId??null,priority:input.priority??null,commitHash:input.commitHash??null,relativeFilePath:input.relativeFilePath??null,lineStart:input.lineStart??null,lineEnd:input.lineEnd??null,tags:normalizeTags(input.tags),status:MemoryStatus.OPEN,resolvedAt:null}))}
 async update(projectId:string,id:string,input:UpdateMemoryDto){const value=await this.one(projectId,id);await this.validate(projectId,{sessionId:input.sessionId??value.sessionId??undefined,commitHash:input.commitHash??value.commitHash??undefined,relativeFilePath:input.relativeFilePath??value.relativeFilePath??undefined,lineStart:input.lineStart??value.lineStart??undefined,lineEnd:input.lineEnd??value.lineEnd??undefined});Object.assign(value,input,{tags:input.tags?normalizeTags(input.tags):value.tags});return this.memories.repository.save(value)}
 async list(projectId:string){if(!await this.projects.existsBy({id:projectId}))throw new NotFoundException('Project was not found');return this.memories.list(projectId)}async one(projectId:string,id:string){const value=await this.memories.one(projectId,id);if(!value)throw new NotFoundException('Memory was not found');return value}
 async resolve(projectId:string,id:string){const value=await this.one(projectId,id);value.status=MemoryStatus.RESOLVED;value.resolvedAt=new Date();return this.memories.repository.save(value)}async archive(projectId:string,id:string){const value=await this.one(projectId,id);value.status=MemoryStatus.ARCHIVED;return this.memories.repository.save(value)}async remove(projectId:string,id:string){await this.one(projectId,id);await this.memories.repository.delete(id)}
 private async validate(projectId:string,input:Partial<CreateMemoryDto>){if(!await this.projects.existsBy({id:projectId}))throw new NotFoundException('Project was not found');validateLineRange(input.lineStart,input.lineEnd);if(input.sessionId&&!await this.sessions.existsBy({id:input.sessionId,projectId}))throw new BadRequestException('Linked session does not belong to this project');if(input.commitHash&&!await this.commits.existsBy({hash:input.commitHash,projectId}))throw new BadRequestException('Linked commit does not belong to this project');if(input.relativeFilePath){const path=normalize(input.relativeFilePath);if(isAbsolute(path)||path==='..'||path.startsWith('../'))throw new BadRequestException('File path must be relative to the project')}}}
